# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transactions.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12transactions.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x81\x01\n\x10SumAmountRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12.\n\nstart_time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12,\n\x08\x65nd_time\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"8\n\x11SumAmountResponse\x12\x0b\n\x03sum\x18\x01 \x01(\x01\x12\x16\n\x0e\x65xecution_time\x18\x02 \x01(\x01\x32\x44\n\x0cTransactions\x12\x34\n\tSumAmount\x12\x11.SumAmountRequest\x1a\x12.SumAmountResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transactions_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SUMAMOUNTREQUEST']._serialized_start=56
  _globals['_SUMAMOUNTREQUEST']._serialized_end=185
  _globals['_SUMAMOUNTRESPONSE']._serialized_start=187
  _globals['_SUMAMOUNTRESPONSE']._serialized_end=243
  _globals['_TRANSACTIONS']._serialized_start=245
  _globals['_TRANSACTIONS']._serialized_end=313
# @@protoc_insertion_point(module_scope)
